WebDevCorp/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebDevCorp.ViewModels
{
    public class ContactForm
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter email address")]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$",
            ErrorMessage = "Please enter correct email address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Please enter a  message")]
        public string Message { get; set; }
    }
}

WebDevCorp/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using WebDevCorp.ViewModels;

namespace WebDevCorp.Controllers
{
    public class ContactController : SurfaceController
    {
        // GET: Contact
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            MailMessage message = new MailMessage();
            message.To.Add("testingumbraco@gmail.com");
            message.Subject = "New Contact request";
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("iamtestingumbraco@gmail.com", "umbracoumbraco!");

                smtp.Send(message);

                TempData["success"] = true;
            }

            IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "Message");
            comment.SetValue("messagename", model.Name);
            comment.SetValue("email", model.Email);
            comment.SetValue("subject", model.Subject);
            comment.SetValue("messageContent", model.Message);

            Services.ContentService.Save(comment);

            return RedirectToCurrentUmbracoPage();
        }
    }
}

WebDevCorp/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.About>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

    <br /><br />
@CurrentPage.GetGridHtml("gridLayout","Bootstrap3")

<br /><br />

WebDevCorp/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}


<div class="container">
<h1>@Umbraco.Field("articleTitle")</h1><br><br>
@Umbraco.Field("articleContents")
</div>

WebDevCorp/Views/Comment.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Comment>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

WebDevCorp/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "MasterLayout.cshtml";
}

<div class="col-xs-6 col-xs-offset-1" style="margin-top: 75px; margin-bottom: 75px;">
    <h3>Contact Us</h3><br /><br />
    <div>@Html.Action("Index", "Contact")</div>
</div>

WebDevCorp/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}

<div id="content" class="container">
        <div class="col-sm-8 mx-auto">
            <p>@Umbraco.Field("mainContent")</p>
            @Umbraco.RenderMacro("listNwestProjects")
        </div>
</div>

WebDevCorp/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "MasterLayout.cshtml";
}

@* the fun starts here *@

@Html.Partial("loginForm")

WebDevCorp/Views/MacroPartials/listNwestProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{ var selection = 
    Model.Content.AncestorOrSelf(1)
    .Children
    .Where(x => x.DocumentTypeAlias== "projectsMain")
    .First()
    .Children
    .Where(x => x.GetPropertyValue<int>("projectStatus") == 28  )
    .OrderBy("CreateDate desc")
    .Take(5); }
   


    <h2>Our projects</h2>
    @foreach (var item in selection)
    {
        <a href="@item.Url"><h4>@item.Name</h4></a><hr/>
    }

WebDevCorp/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web



@{ var selection = Model.Content.Site().Children.Where(x => x.IsVisible()).ToArray(); }

@if (selection.Length > 0)
{
    <ul class="navbar-nav mr-auto">
        <h1>@Umbraco.Field("projectStatus")</h1>
        <li class="nav-item">
            <a class="nav-link" href="/@Model.Content.Site().Name">Home</a>
        </li>
        @foreach (var item in selection)
        {

            var isProtected = umbraco.library.IsProtected(item.Id, item.Path);
            var loginAccess = umbraco.library.IsProtected(item.Id, item.Path) && umbraco.library.HasAccess(item.Id, item.Path);
            if (!isProtected || loginAccess)
            {
                var selectionDropDown = item.Children.Where(x => x.IsVisible()).OrderBy(x => x.Name).ToArray();

                if (selectionDropDown.Length > 0)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="download" aria-expanded="false">@item.Name <span class="caret"></span></a>
                        <div class="dropdown-menu" aria-labelledby="download">
                            <a class="dropdown-item" href="@item.Url">@item.Name</a>
                            <div class="dropdown-divider"></div>
                            @foreach (var item2 in selectionDropDown)
                            {
                                if (item2.GetProperty("projectStatus") != null && item2.GetPropertyValue("projectStatus").ToString() == "28")
                                {
                                    <a class="dropdown-item" href="@item2.Url">@item2.Name</a>
                                }
                                else if (item2.GetProperty("projectStatus") == null)
                                {
                                    <a class="dropdown-item" href="@item2.Url">@item2.Name</a>
                                }

                            }
                        </div>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@item.Url">@item.Name</a>
                    </li>
                }
            }






        }

    </ul>
}

WebDevCorp/Views/MacroPartials/sitemap.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Core.Models
@using Umbraco.Web


@*
    This snippet makes a list of links of all visible pages of the site, as nested unordered HTML lists.

    How it works:
    - It uses a custom Razor helper called Traverse() to select and display the markup and links.
*@

@{ var selection = Model.Content.Site(); }

<div class="sitemap">
    @* Render the sitemap by passing the root node to the traverse helper, below *@
    @Traverse(selection)
</div>


@* Helper method to traverse through all descendants *@
@helper Traverse(IPublishedContent node)
{
    @* Update the level to reflect how deep you want the sitemap to go *@
    const int maxLevelForSitemap = 4;

    @* Select visible children *@
    var selection = node.Children.Where(x => x.IsVisible() && x.Level <= maxLevelForSitemap).ToArray();

    @* If any items are returned, render a list *@
    if (selection.Length > 0)
    {
        <ul>
            @foreach (var item in selection)
            {
                <li class="level-@item.Level">
                    <a href="@item.Url">@item.Name</a>

                    @* Run the traverse helper again for any child pages *@
                    @Traverse(item)
                </li>
            }
        </ul>
    }
}

WebDevCorp/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = null;
}

@* the fun starts here *@
  <!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/Site.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha256-ZT4HPpdCOt2lvDkXokHuhJfdOKSPFLzeAJik5U/Q+l4=" crossorigin="anonymous" />
    
  </head>
<body style="background: #ccc;">
	<div id="header-container">
		<header class="wrapper clearfix">
			
			<nav role="navigation">
                 @Umbraco.RenderMacro("mainNav")
          </nav>
		
		</header>
	</div>
	<div id="main-container">
		<div id="main" class="wrapper clearfix">
			
		</div> <!-- #main -->
		<div class="container" style="background: white;">@RenderBody()</div>
			
	</div> <!-- #main-container -->
	<div id="footer-container">
		<footer class="wrapper">
			<h3>@Umbraco.Field("footer")</h3>
		</footer>
	</div>

</body>
</html>

WebDevCorp/Views/MemberArea.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MemberArea>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

WebDevCorp/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Members>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}


@{
var memberService = ApplicationContext.Current.Services.MemberService;

var activeMembers = memberService.GetMembersByGroup("Active");
var prospectMembers = memberService.GetMembersByGroup("Prospect");
}

<div class="row">
    <div class="col-xs-6">
        <h1 class="text-center">Active members</h1>

        @foreach (var member in activeMembers)
        {
            string fullPath = member.GetValue("photo").ToString();
            string[] substrings = fullPath.Split(',');
            string srcString = substrings[2];
            string[] srcSubStrings = srcString.Split(':');
            string srcPath = srcSubStrings[1].Replace("\"", "");
            srcPath = srcPath.Replace("}", "");

        <div class="col-xs-6 col-xs-offset-3" style="padding: 30px;">
            <p>Name: <strong> @member.Name</strong></p>
            <img style="width:400px; height: auto; margin: 0 auto;" class="img-responsive" src="@srcPath" />
            <p>Username: @member.Username</p>
            <p><i>Email: @member.Email</i></p>
        </div>
        }

    </div>

    <div class="col-xs-6">
        <h1 class="text-center">Prospect members</h1>

        @foreach (var member in prospectMembers)
        {
            <div style="padding: 30px;">
                <p>Name: <strong> @member.Name</strong></p>
                <p><i>Email: @member.Email</i></p>
                <p>Username: @member.Username</p>
            </div>
        }
    </div>
</div>

WebDevCorp/Views/MessageBoard.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MessageBoard>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

<div class="col-xs-8 col-xs-offset-1" style="margin-top: 75px; margin-bottom: 75px;">
    <h3>Comments</h3><br /><br />
    @Html.Action("Index", "Message")
    @Umbraco.RenderMacro("messagemenu")
</div>


<br /><br />

WebDevCorp/Views/Partials/ContactForm.cshtml
@model WebDevCorp.ViewModels.ContactForm
@{
    Layout = null;
}

@if (TempData["success"] == null)
{
    using (Html.BeginUmbracoForm("HandleFormSubmit", "Contact", new object { }, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })

            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Send</button>
            </div>
        </div>
    }
}
else
{
    <p> Thank you for contacting us. We’ll be in touch soon! </p>
}

WebDevCorp/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

WebDevCorp/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

WebDevCorp/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

WebDevCorp/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

WebDevCorp/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

WebDevCorp/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

WebDevCorp/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

WebDevCorp/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

WebDevCorp/Views/ProjectsItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ProjectsItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "MasterLayout.cshtml";
}

<div class="container">
<h1>@Umbraco.Field("projectTitle")</h1><br><br>
@Umbraco.Field("projectContents")
@Umbraco.Field("projectStatus")
</div>